# Generated by Django 5.0.3 on 2024-03-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_cover_lesson_index_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
